name: Run tests in Answers

on:
  push:
    branches:
      - master
      - add_ci_pipeline
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_day1:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]
        include:
          - dotnet-version: 8.0.x
            framework: net8.0

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: List installed .NET SDKs
        run: dotnet --list-sdks

      - name: Restore project dependencies
        working-directory: ./csharp/SdetBootcampDay1
        run: dotnet restore -p:TargetFramework=${{ matrix.framework }}

      - name: Build the project
        working-directory: ./csharp/SdetBootcampDay1
        run: dotnet build --framework ${{ matrix.framework }} --no-restore

      - name: Run tests from day 1
        working-directory: ./csharp/SdetBootcampDay1
        run: dotnet test --framework ${{ matrix.framework }} --no-restore --no-build --verbosity normal --filter Name~Answers

  build_day2:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]
        include:
          - dotnet-version: 8.0.x
            framework: net8.0

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: List installed .NET SDKs
        run: dotnet --list-sdks

      - name: Restore project dependencies
        working-directory: ./csharp/SdetBootcampDay2
        run: dotnet restore -p:TargetFramework=${{ matrix.framework }}

      - name: Build the project
        working-directory: ./csharp/SdetBootcampDay2
        run: dotnet build --framework ${{ matrix.framework }} --no-restore

      - name: Run tests from day 2 
        working-directory: ./csharp/SdetBootcampDay2
        run: dotnet test --framework ${{ matrix.framework }} --no-restore --no-build --verbosity normal --filter Name~Answers
# - Cypress work in progress -  
#  build_cypress:  
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        dotnet-version: [8.0.x]
#        include:
#          - dotnet-version: 8.0.x
#            framework: net8.0
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: ${{ matrix.dotnet-version }}
#
#      - name: List installed .NET SDKs
#        run: dotnet --list-sdks
#
#      - name: Restore project dependencies
#        working-directory: ./csharp/SdetBootcampDay2
#        run: dotnet restore -p:TargetFramework=${{ matrix.framework }}
#
#      - name: Build the project
#        working-directory: ./csharp/SdetBootcampDay2
#        run: dotnet build --framework ${{ matrix.framework }} --no-restore
#
#      - name: Run tests from day 2 
#        working-directory: ./csharp/SdetBootcampDay2
#        run: dotnet test --framework ${{ matrix.framework }} --no-restore --no-build --verbosity normal --filter Name~Answers
#